# Generated by Django 4.0.4 on 2022-05-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='imaurl',
            field=models.URLField(default=200, max_length=300),
            preserve_default=False,
        ),
    ]
