# Generated by Django 4.0.4 on 2022-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_livre_imaurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='imaurl',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
