# Generated by Django 4.0.4 on 2022-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0005_alter_livre_imaurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
