# Generated by Django 4.0.4 on 2022-05-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0006_alter_livre_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='nom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.nom'),
        ),
    ]
