# Generated by Django 4.0.4 on 2022-05-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0007_livre_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='nom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.nom'),
        ),
    ]
